name: Update docs

on:
  workflow_dispatch:
  gollum:

jobs:
  docs: 
    runs-on: arc-runner-k8s
    permissions:
      actions: write
      contents: write
    steps:
      # - name: Generate a token
      #   id: generate_token
      #   uses: actions/create-github-app-token@v1
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.APP_PEM }}
      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ steps.generate_token.outputs.token }}
      #     repository: unipoll/gollum-test
      #     event-type: update_submodules
      - name: Install curl
        run: |
          sudo apt update
          sudo apt install curl -y
          sudo apt install jq -y
      - name: Generate JWT and token
        id: generate-github-app-tokens
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        with:
          app-id: ${{ secrets.APP_ID}}
          app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          private-key: ${{ secrets.APP_PEM }}
      - name: Trigger the action
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.generate-github-app-tokens.outputs.jwt }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/unipoll/gollum-test/dispatches \
          -d '{"event_type":"update_submodules"}'