name: Update docs

on:
  workflow_dispatch:
  gollum:

jobs:
  docs: 
    runs-on: arc-runner-k8s
    permissions:
      actions: write
      contents: write
    steps:
      # - name: Generate a token
      #   id: app-token
      #   uses: actions/create-github-app-token@v1
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.APP_PEM }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEMP_PAT }}
          repository: unipoll/gollum-test
          event-type: update_submodules