# Test Angular app
name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: arc-runner-k8s

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Install wget
      run: |
        sudo apt update
        sudo apt install wget -y
    - name: Install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb -y
    - run: chrome --version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox